name: Test, build, publish

on:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.version_check.outputs.current_version }}
      previous_version: ${{ steps.version_check.outputs.previous_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.9.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Check version
        id: version_check
        run: |
          sudo apt-get install -y jq
          echo "current_version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
          echo "previous_version=$(yarn npm info $(jq -r .name package.json) -f version --json | jq -r .version)" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: test_and_build
    if: ${{ needs.test_and_build.outputs.current_version != needs.test_and_build.outputs.previous_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.9.0'
          cache: 'yarn'

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Publish to npm
        run: yarn npm publish --access public
